// <auto-generated />
using System;
using System.Collections.Generic;
using Expenses.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Expenses.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ExpensesDbContext))]
    [Migration("20260825195730_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Expenses.Domain.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_code");

                    b.HasIndex("ParentId");

                    b.ToTable("categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_categories_name_length", "length(name) <= 256");
                        });
                });

            modelBuilder.Entity("Expenses.Domain.Expense", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("CategoryRaw")
                        .HasColumnType("text")
                        .HasColumnName("category_raw");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("discount_amount");

                    b.Property<decimal?>("ListUnitPrice")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("list_unit_price");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.Property<long?>("UnitId")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_id");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("unit_price");

                    b.Property<string>("UnitRaw")
                        .HasColumnType("text")
                        .HasColumnName("unit_raw");

                    b.Property<long?>("purchase_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Description")
                        .HasDatabaseName("ix_expenses_description_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Description"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Description"), new[] { "gin_trgm_ops" });

                    b.HasIndex("UnitId");

                    b.HasIndex("purchase_id");

                    b.ToTable("expenses", null, t =>
                        {
                            t.HasCheckConstraint("ck_expenses_category_raw_length", "category_raw IS NULL OR length(category_raw) <= 256");

                            t.HasCheckConstraint("ck_expenses_description_length", "length(description) <= 512");

                            t.HasCheckConstraint("ck_expenses_unit_raw_length", "unit_raw IS NULL OR length(unit_raw) <= 128");
                        });
                });

            modelBuilder.Entity("Expenses.Domain.Extraction.ExtractionCandidate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("CategoryRaw")
                        .HasColumnType("text")
                        .HasColumnName("category_raw");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("discount_amount");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<decimal?>("ListUnitPrice")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("list_unit_price");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("provenance");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.Property<string>("ReportedConfidence")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reported_confidence");

                    b.Property<long?>("UnitId")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_id");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("unit_price");

                    b.Property<string>("UnitRaw")
                        .HasColumnType("text")
                        .HasColumnName("unit_raw");

                    b.Property<long?>("extraction_result_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("extraction_result_id");

                    b.ToTable("extraction_candidates", (string)null);
                });

            modelBuilder.Entity("Expenses.Domain.Extraction.ExtractionResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("EngineName")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("engine_name");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasColumnType("varchar(32)")
                        .HasColumnName("engine_version");

                    b.Property<string>("MerchantName")
                        .HasColumnType("text")
                        .HasColumnName("merchant_name");

                    b.Property<string>("MerchantTaxId")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("merchant_tax_id");

                    b.Property<string>("Provenance")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("provenance");

                    b.Property<long>("ReceiptImageId")
                        .HasColumnType("bigint")
                        .HasColumnName("receipt_image_id");

                    b.Property<string>("ReportedConfidence")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reported_confidence");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal?>("TaxRatePercent")
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("tax_rate_percent");

                    b.Property<decimal?>("Total")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("total");

                    b.PrimitiveCollection<List<string>>("_stagesRun")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("stages_run");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptImageId");

                    b.ToTable("extraction_results", (string)null);
                });

            modelBuilder.Entity("Expenses.Domain.Merchant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<string>("TaxId")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("tax_id");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_merchants_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("ParentId");

                    b.HasIndex("TaxId")
                        .IsUnique()
                        .HasDatabaseName("ix_merchants_tax_id")
                        .HasFilter("tax_id IS NOT NULL");

                    b.ToTable("merchants", null, t =>
                        {
                            t.HasCheckConstraint("ck_merchants_name_length", "length(name) <= 256");
                        });
                });

            modelBuilder.Entity("Expenses.Domain.Purchase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<long?>("MerchantId")
                        .HasColumnType("bigint")
                        .HasColumnName("merchant_id");

                    b.Property<string>("MerchantRaw")
                        .HasColumnType("text")
                        .HasColumnName("merchant_raw");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("occurred_at");

                    b.Property<long?>("ReceiptImageId")
                        .HasColumnType("bigint")
                        .HasColumnName("receipt_image_id");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.HasIndex("MerchantRaw")
                        .HasDatabaseName("ix_purchases_merchant_raw_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("MerchantRaw"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("MerchantRaw"), new[] { "gin_trgm_ops" });

                    b.HasIndex("ReceiptImageId");

                    b.HasIndex("OccurredAt", "Amount")
                        .IsUnique()
                        .HasDatabaseName("ix_purchases_occurred_at_amount");

                    b.ToTable("purchases", null, t =>
                        {
                            t.HasCheckConstraint("ck_purchases_merchant_raw_length", "merchant_raw IS NULL OR length(merchant_raw) <= 512");
                        });
                });

            modelBuilder.Entity("Expenses.Domain.ReceiptImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("ContentHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content_hash");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .HasColumnName("content_type");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<int>("FiscalExtractedSource")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_extracted_source");

                    b.Property<string>("FiscalIkofExtracted")
                        .HasColumnType("text")
                        .HasColumnName("fiscal_ikof_extracted");

                    b.Property<string>("FiscalIkofSupplied")
                        .HasColumnType("text")
                        .HasColumnName("fiscal_ikof_supplied");

                    b.Property<string>("FiscalJikrExtracted")
                        .HasColumnType("text")
                        .HasColumnName("fiscal_jikr_extracted");

                    b.Property<string>("FiscalJikrSupplied")
                        .HasColumnType("text")
                        .HasColumnName("fiscal_jikr_supplied");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_in_bytes");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique()
                        .HasDatabaseName("ix_receipt_images_content_hash");

                    b.ToTable("receipt_images", null, t =>
                        {
                            t.HasCheckConstraint("ck_receipt_images_content_hash_length", "length(content_hash) = 32");
                        });
                });

            modelBuilder.Entity("Expenses.Domain.Unit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("symbol");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_units_code");

                    b.ToTable("units", null, t =>
                        {
                            t.HasCheckConstraint("ck_units_name_length", "length(name) <= 128");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "PCS",
                            IsActive = true,
                            Kind = 0,
                            Name = "Piece",
                            Symbol = "pcs"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "PACK",
                            IsActive = true,
                            Kind = 0,
                            Name = "Pack",
                            Symbol = "pack"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "BUNCH",
                            IsActive = true,
                            Kind = 0,
                            Name = "Bunch",
                            Symbol = "bunch"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "KG",
                            IsActive = true,
                            Kind = 1,
                            Name = "Kilogram",
                            Symbol = "kg"
                        },
                        new
                        {
                            Id = 5L,
                            Code = "G",
                            IsActive = true,
                            Kind = 1,
                            Name = "Gram",
                            Symbol = "g"
                        },
                        new
                        {
                            Id = 6L,
                            Code = "L",
                            IsActive = true,
                            Kind = 2,
                            Name = "Litre",
                            Symbol = "l"
                        },
                        new
                        {
                            Id = 7L,
                            Code = "ML",
                            IsActive = true,
                            Kind = 2,
                            Name = "Millilitre",
                            Symbol = "ml"
                        });
                });

            modelBuilder.Entity("Expenses.Infrastructure.Persistence.Configurations.ReceiptImageContentRow", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.HasKey("Id");

                    b.ToTable("receipt_images", (string)null);
                });

            modelBuilder.Entity("Expenses.Domain.Category", b =>
                {
                    b.HasOne("Expenses.Domain.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Expenses.Domain.Expense", b =>
                {
                    b.HasOne("Expenses.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Expenses.Domain.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Expenses.Domain.Purchase", null)
                        .WithMany("Expenses")
                        .HasForeignKey("purchase_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Expenses.Domain.Extraction.ExtractionCandidate", b =>
                {
                    b.HasOne("Expenses.Domain.Extraction.ExtractionResult", null)
                        .WithMany("Candidates")
                        .HasForeignKey("extraction_result_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Expenses.Domain.Extraction.ExtractionResult", b =>
                {
                    b.HasOne("Expenses.Domain.ReceiptImage", null)
                        .WithMany()
                        .HasForeignKey("ReceiptImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Expenses.Domain.Merchant", b =>
                {
                    b.HasOne("Expenses.Domain.Merchant", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Expenses.Domain.Purchase", b =>
                {
                    b.HasOne("Expenses.Domain.Merchant", null)
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Expenses.Domain.ReceiptImage", null)
                        .WithMany()
                        .HasForeignKey("ReceiptImageId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Expenses.Infrastructure.Persistence.Configurations.ReceiptImageContentRow", b =>
                {
                    b.HasOne("Expenses.Domain.ReceiptImage", null)
                        .WithOne()
                        .HasForeignKey("Expenses.Infrastructure.Persistence.Configurations.ReceiptImageContentRow", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Expenses.Domain.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Expenses.Domain.Extraction.ExtractionResult", b =>
                {
                    b.Navigation("Candidates");
                });

            modelBuilder.Entity("Expenses.Domain.Merchant", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Expenses.Domain.Purchase", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
