// <auto-generated />
using System;
using Expenses.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Expenses.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ExpensesDbContext))]
    [Migration("20260902135830_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Expenses.Domain.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_code");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_categories_parent_id");

                    b.ToTable("categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_categories_name_length", "length(name) <= 256");
                        });
                });

            modelBuilder.Entity("Expenses.Domain.Expense", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,2)")
                        .HasColumnName("amount");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<string>("CategoryRaw")
                        .HasColumnType("text")
                        .HasColumnName("category_raw");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("numeric(19,2)")
                        .HasColumnName("discount_amount");

                    b.Property<decimal?>("ListUnitPrice")
                        .HasColumnType("numeric(19,2)")
                        .HasColumnName("list_unit_price");

                    b.Property<long?>("PurchaseId")
                        .HasColumnType("bigint")
                        .HasColumnName("purchase_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.Property<long?>("UnitId")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_id");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("numeric(19,2)")
                        .HasColumnName("unit_price");

                    b.Property<string>("UnitRaw")
                        .HasColumnType("text")
                        .HasColumnName("unit_raw");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_expenses_category_id");

                    b.HasIndex("Description")
                        .HasDatabaseName("ix_expenses_description_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Description"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Description"), new[] { "gin_trgm_ops" });

                    b.HasIndex("PurchaseId")
                        .HasDatabaseName("ix_expenses_purchase_id");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_expenses_unit_id");

                    b.ToTable("expenses", null, t =>
                        {
                            t.HasCheckConstraint("ck_expenses_category_raw_length", "category_raw IS NULL OR length(category_raw) <= 256");

                            t.HasCheckConstraint("ck_expenses_description_length", "length(description) <= 512");

                            t.HasCheckConstraint("ck_expenses_unit_raw_length", "unit_raw IS NULL OR length(unit_raw) <= 128");
                        });
                });

            modelBuilder.Entity("Expenses.Domain.Merchant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id");

                    b.Property<string>("TaxId")
                        .HasColumnType("varchar(32)")
                        .HasColumnName("tax_id");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_merchants_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_merchants_parent_id");

                    b.HasIndex("TaxId")
                        .IsUnique()
                        .HasDatabaseName("ix_merchants_tax_id")
                        .HasFilter("tax_id IS NOT NULL");

                    b.ToTable("merchants", null, t =>
                        {
                            t.HasCheckConstraint("ck_merchants_name_length", "length(name) <= 256");
                        });
                });

            modelBuilder.Entity("Expenses.Domain.Purchase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,2)")
                        .HasColumnName("amount");

                    b.Property<long?>("MerchantId")
                        .HasColumnType("bigint")
                        .HasColumnName("merchant_id");

                    b.Property<string>("MerchantRaw")
                        .HasColumnType("text")
                        .HasColumnName("merchant_raw");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("occurred_at");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId")
                        .HasDatabaseName("ix_purchases_merchant_id");

                    b.HasIndex("MerchantRaw")
                        .HasDatabaseName("ix_purchases_merchant_raw_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("MerchantRaw"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("MerchantRaw"), new[] { "gin_trgm_ops" });

                    b.HasIndex("OccurredAt", "Amount")
                        .IsUnique()
                        .HasDatabaseName("ix_purchases_occurred_at_amount");

                    b.ToTable("purchases", null, t =>
                        {
                            t.HasCheckConstraint("ck_purchases_merchant_raw_length", "merchant_raw IS NULL OR length(merchant_raw) <= 512");

                            t.HasCheckConstraint("ck_purchases_receipt_all_or_nothing", "(receipt_content_hash IS NULL AND receipt_storage_key IS NULL AND receipt_content_type IS NULL\n    AND receipt_size_in_bytes IS NULL AND receipt_state IS NULL)\nOR (receipt_content_hash IS NOT NULL AND receipt_storage_key IS NOT NULL\n    AND receipt_content_type IS NOT NULL AND receipt_size_in_bytes IS NOT NULL\n    AND receipt_state IS NOT NULL)");

                            t.HasCheckConstraint("ck_purchases_receipt_content_hash_length", "receipt_content_hash IS NULL OR length(receipt_content_hash) = 32");

                            t.HasCheckConstraint("ck_purchases_receipt_storage_key_length", "receipt_storage_key IS NULL OR length(receipt_storage_key) <= 256");
                        });
                });

            modelBuilder.Entity("Expenses.Domain.Unit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("symbol");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_units_code");

                    b.ToTable("units", null, t =>
                        {
                            t.HasCheckConstraint("ck_units_name_length", "length(name) <= 128");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "PCS",
                            IsActive = true,
                            Kind = 0,
                            Name = "Piece",
                            Symbol = "pcs"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "PACK",
                            IsActive = true,
                            Kind = 0,
                            Name = "Pack",
                            Symbol = "pack"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "BUNCH",
                            IsActive = true,
                            Kind = 0,
                            Name = "Bunch",
                            Symbol = "bunch"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "KG",
                            IsActive = true,
                            Kind = 1,
                            Name = "Kilogram",
                            Symbol = "kg"
                        },
                        new
                        {
                            Id = 5L,
                            Code = "G",
                            IsActive = true,
                            Kind = 1,
                            Name = "Gram",
                            Symbol = "g"
                        },
                        new
                        {
                            Id = 6L,
                            Code = "L",
                            IsActive = true,
                            Kind = 2,
                            Name = "Litre",
                            Symbol = "l"
                        },
                        new
                        {
                            Id = 7L,
                            Code = "ML",
                            IsActive = true,
                            Kind = 2,
                            Name = "Millilitre",
                            Symbol = "ml"
                        });
                });

            modelBuilder.Entity("Expenses.Domain.Category", b =>
                {
                    b.HasOne("Expenses.Domain.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_categories_categories_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Expenses.Domain.Expense", b =>
                {
                    b.HasOne("Expenses.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_expenses_categories_category_id");

                    b.HasOne("Expenses.Domain.Purchase", null)
                        .WithMany("Expenses")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_expenses_purchases_purchase_id");

                    b.HasOne("Expenses.Domain.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_expenses_units_unit_id");
                });

            modelBuilder.Entity("Expenses.Domain.Merchant", b =>
                {
                    b.HasOne("Expenses.Domain.Merchant", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_merchants_merchants_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Expenses.Domain.Purchase", b =>
                {
                    b.HasOne("Expenses.Domain.Merchant", null)
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_purchases_merchants_merchant_id");

                    b.OwnsOne("Expenses.Domain.Receipt", "Receipt", b1 =>
                        {
                            b1.Property<long>("PurchaseId")
                                .HasColumnType("bigint");

                            b1.Property<byte[]>("ContentHash")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("receipt_content_hash");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("varchar(128)")
                                .HasColumnName("receipt_content_type");

                            b1.Property<string>("FailureReason")
                                .HasColumnType("text")
                                .HasColumnName("receipt_failure_reason");

                            b1.Property<int>("FiscalExtractedSource")
                                .HasColumnType("integer")
                                .HasColumnName("fiscal_extracted_source");

                            b1.Property<string>("FiscalIkofExtracted")
                                .HasColumnType("text")
                                .HasColumnName("fiscal_ikof_extracted");

                            b1.Property<string>("FiscalIkofSupplied")
                                .HasColumnType("text")
                                .HasColumnName("fiscal_ikof_supplied");

                            b1.Property<string>("FiscalJikrExtracted")
                                .HasColumnType("text")
                                .HasColumnName("fiscal_jikr_extracted");

                            b1.Property<string>("FiscalJikrSupplied")
                                .HasColumnType("text")
                                .HasColumnName("fiscal_jikr_supplied");

                            b1.Property<long>("SizeInBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("receipt_size_in_bytes");

                            b1.Property<int>("State")
                                .HasColumnType("integer")
                                .HasColumnName("receipt_state");

                            b1.Property<string>("StorageKey")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("receipt_storage_key");

                            b1.HasKey("PurchaseId");

                            b1.HasIndex("ContentHash")
                                .HasDatabaseName("ix_purchases_receipt_content_hash");

                            b1.ToTable("purchases");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseId");
                        });

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("Expenses.Domain.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Expenses.Domain.Merchant", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Expenses.Domain.Purchase", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
