// <auto-generated />
using System;
using Expenses.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Expenses.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ExpensesDbContext))]
    [Migration("20260828132914_PascalCaseIdentifiers")]
    partial class PascalCaseIdentifiers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Expenses.Domain.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_code");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_categories_name_length", "length(\"Name\") <= 256");
                        });
                });

            modelBuilder.Entity("Expenses.Domain.Expense", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,2)");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<string>("CategoryRaw")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("numeric(19,2)");

                    b.Property<decimal?>("ListUnitPrice")
                        .HasColumnType("numeric(19,2)");

                    b.Property<long?>("PurchaseId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(12,3)");

                    b.Property<long?>("UnitId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("numeric(19,2)");

                    b.Property<string>("UnitRaw")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Description")
                        .HasDatabaseName("ix_expenses_description_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Description"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Description"), new[] { "gin_trgm_ops" });

                    b.HasIndex("PurchaseId");

                    b.HasIndex("UnitId");

                    b.ToTable("Expenses", null, t =>
                        {
                            t.HasCheckConstraint("ck_expenses_category_raw_length", "\"CategoryRaw\" IS NULL OR length(\"CategoryRaw\") <= 256");

                            t.HasCheckConstraint("ck_expenses_description_length", "length(\"Description\") <= 512");

                            t.HasCheckConstraint("ck_expenses_unit_raw_length", "\"UnitRaw\" IS NULL OR length(\"UnitRaw\") <= 128");
                        });
                });

            modelBuilder.Entity("Expenses.Domain.Merchant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("TaxId")
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_merchants_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("ParentId");

                    b.HasIndex("TaxId")
                        .IsUnique()
                        .HasDatabaseName("ix_merchants_tax_id")
                        .HasFilter("\"TaxId\" IS NOT NULL");

                    b.ToTable("Merchants", null, t =>
                        {
                            t.HasCheckConstraint("ck_merchants_name_length", "length(\"Name\") <= 256");
                        });
                });

            modelBuilder.Entity("Expenses.Domain.Purchase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,2)");

                    b.Property<long?>("MerchantId")
                        .HasColumnType("bigint");

                    b.Property<string>("MerchantRaw")
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.HasIndex("MerchantRaw")
                        .HasDatabaseName("ix_purchases_merchant_raw_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("MerchantRaw"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("MerchantRaw"), new[] { "gin_trgm_ops" });

                    b.HasIndex("OccurredAt", "Amount")
                        .IsUnique()
                        .HasDatabaseName("ix_purchases_occurred_at_amount");

                    b.ToTable("Purchases", null, t =>
                        {
                            t.HasCheckConstraint("ck_purchases_merchant_raw_length", "\"MerchantRaw\" IS NULL OR length(\"MerchantRaw\") <= 512");

                            t.HasCheckConstraint("ck_purchases_receipt_all_or_nothing", "(\"ReceiptContentHash\" IS NULL AND \"ReceiptStorageKey\" IS NULL AND \"ReceiptContentType\" IS NULL\n    AND \"ReceiptSizeInBytes\" IS NULL AND \"ReceiptState\" IS NULL)\nOR (\"ReceiptContentHash\" IS NOT NULL AND \"ReceiptStorageKey\" IS NOT NULL\n    AND \"ReceiptContentType\" IS NOT NULL AND \"ReceiptSizeInBytes\" IS NOT NULL\n    AND \"ReceiptState\" IS NOT NULL)");

                            t.HasCheckConstraint("ck_purchases_receipt_content_hash_length", "\"ReceiptContentHash\" IS NULL OR length(\"ReceiptContentHash\") = 32");

                            t.HasCheckConstraint("ck_purchases_receipt_storage_key_length", "\"ReceiptStorageKey\" IS NULL OR length(\"ReceiptStorageKey\") <= 256");
                        });
                });

            modelBuilder.Entity("Expenses.Domain.Unit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_units_code");

                    b.ToTable("Units", null, t =>
                        {
                            t.HasCheckConstraint("ck_units_name_length", "length(\"Name\") <= 128");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "PCS",
                            IsActive = true,
                            Kind = 0,
                            Name = "Piece",
                            Symbol = "pcs"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "PACK",
                            IsActive = true,
                            Kind = 0,
                            Name = "Pack",
                            Symbol = "pack"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "BUNCH",
                            IsActive = true,
                            Kind = 0,
                            Name = "Bunch",
                            Symbol = "bunch"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "KG",
                            IsActive = true,
                            Kind = 1,
                            Name = "Kilogram",
                            Symbol = "kg"
                        },
                        new
                        {
                            Id = 5L,
                            Code = "G",
                            IsActive = true,
                            Kind = 1,
                            Name = "Gram",
                            Symbol = "g"
                        },
                        new
                        {
                            Id = 6L,
                            Code = "L",
                            IsActive = true,
                            Kind = 2,
                            Name = "Litre",
                            Symbol = "l"
                        },
                        new
                        {
                            Id = 7L,
                            Code = "ML",
                            IsActive = true,
                            Kind = 2,
                            Name = "Millilitre",
                            Symbol = "ml"
                        });
                });

            modelBuilder.Entity("Expenses.Domain.Category", b =>
                {
                    b.HasOne("Expenses.Domain.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Expenses.Domain.Expense", b =>
                {
                    b.HasOne("Expenses.Domain.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Expenses.Domain.Purchase", null)
                        .WithMany("Expenses")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Expenses.Domain.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Expenses.Domain.Merchant", b =>
                {
                    b.HasOne("Expenses.Domain.Merchant", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Expenses.Domain.Purchase", b =>
                {
                    b.HasOne("Expenses.Domain.Merchant", null)
                        .WithMany()
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Expenses.Domain.Receipt", "Receipt", b1 =>
                        {
                            b1.Property<long>("PurchaseId")
                                .HasColumnType("bigint");

                            b1.Property<byte[]>("ContentHash")
                                .IsRequired()
                                .HasColumnType("bytea")
                                .HasColumnName("ReceiptContentHash");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("varchar(128)")
                                .HasColumnName("ReceiptContentType");

                            b1.Property<string>("FailureReason")
                                .HasColumnType("text")
                                .HasColumnName("ReceiptFailureReason");

                            b1.Property<int>("FiscalExtractedSource")
                                .HasColumnType("integer")
                                .HasColumnName("FiscalExtractedSource");

                            b1.Property<string>("FiscalIkofExtracted")
                                .HasColumnType("text")
                                .HasColumnName("FiscalIkofExtracted");

                            b1.Property<string>("FiscalIkofSupplied")
                                .HasColumnType("text")
                                .HasColumnName("FiscalIkofSupplied");

                            b1.Property<string>("FiscalJikrExtracted")
                                .HasColumnType("text")
                                .HasColumnName("FiscalJikrExtracted");

                            b1.Property<string>("FiscalJikrSupplied")
                                .HasColumnType("text")
                                .HasColumnName("FiscalJikrSupplied");

                            b1.Property<long>("SizeInBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("ReceiptSizeInBytes");

                            b1.Property<int>("State")
                                .HasColumnType("integer")
                                .HasColumnName("ReceiptState");

                            b1.Property<string>("StorageKey")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ReceiptStorageKey");

                            b1.HasKey("PurchaseId");

                            b1.HasIndex("ContentHash")
                                .HasDatabaseName("ix_purchases_receipt_content_hash");

                            b1.ToTable("Purchases");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseId");
                        });

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("Expenses.Domain.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Expenses.Domain.Merchant", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Expenses.Domain.Purchase", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
